version: '3.9'

services:
  web:
    build: .
    ports:
      - '8000:8000'
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    depends_on:
      - db
  db:
    image: postgres:14
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/data/db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres_data: {}